spring:
  kafka:
    bootstrap-server: localhost:9092
    producer:
      key.serializer: org.apache.kafka.common.serialization.StringSerializer
      value.serializer: ru.yandex.practicum.serializer.CollectorSerializer
grpc:
  server:
    port: 9090