spring:
  application:
    name: aggregator
  config:
    import: "configserver:"

  cloud:
    config:
      fail-fast: true
      retry:
        userRandomPolicy: true
        max-interval: 6000
      discovery:
        enabled: true
        serviceId: config-server

#  config:
#    import: configserver:http://localhost:8888
##  cloud:
#    config:
#      fail-fast: true
#      retry:
#        userRandomPolicy: true
#        max-interval: 6000

server:
  port: 0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka