analyzer:
  kafka:
    bootstrap-server: localhost:9092
    key-serializer: org.apache.kafka.common.serialization.StringSerializer
    value-serializer: ru.yandex.practicum.serializer.CollectorSerializer
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-snapshot-deserializer: ru.yandex.practicum.deserializer.SensorsSnapshotAvroDeserializer
    value-hub-deserializer: ru.yandex.practicum.deserializer.HubEventAvroDeserializer
    group-id: analyzer-consumer-client
    snapshots-topic: telemetry.snapshots.v1
    collector-topic-sensor: telemetry.sensors.v1
    collector-topic-hub: telemetry.hubs.v1
    max-poll-records: 100
    max-poll-interval-ms: 30000
    fetch-max-wait-ms: 100

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        jdbc.time_zone: UTC
        format_sql: true
    show_sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql.init.mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345
  sql:
    init:
      mode: always