kafka:
  config:
    bootstrap-servers: localhost:9092
    key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    value-snapshot-deserializer: ru.yandex.practicum.deserializer.SensorsSnapshotAvroDeserializer
    value-hub-deserializer: ru.yandex.practicum.deserializer.HubEventAvroDeserializer
    group-snapshot: analyzer-group-snapshot
    group-hub: analyzer-group-hub
    fetch-max-wait-ms: 100
    max-poll-records-config: 100
    enable-auto-commit: false
    topic-snapshots: telemetry.snapshots.v1
    topic-hubs: telemetry.hubs.v1
    consume-attempt-timeout: 100

grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

spring:
  jpa:
    hibernate.ddl-auto: none
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
        format_sql: true
    show_sql: true
  database-platform: org.hibernate.dialect.PostgreSQLDialect
  sql.init.mode: always
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345
  sql:
    init:
      mode: always